name: Generate Project
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Clean install
      run: "mvn -B clean install"

